*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZTFIAAC001_1U01.
                    "TABLEFRAME_ZTFIAAC001_1
INCLUDE LZTFIAAC001_1U02.
                    "TABLEPROC_ZTFIAAC001_1