*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZCXR1000_2U01.
                    "ZCX_ZTCXR1000_2_WRITE_DOCUMENT