*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZTFIF1001_1U01.
                    "VIEWFRAME_ZVFIF1001_1
INCLUDE LZTFIF1001_1U02.
                    "VIEWPROC_ZVFIF1001_1