*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZTMME1006_2U01.
                    "VIEWFRAME_ZVMME1006_2
INCLUDE LZTMME1006_2U02.
                    "VIEWPROC_ZVMME1006_2