*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZVCXR1000_1U01.
                    "VIEWFRAME_ZVCXR1000_1
INCLUDE LZVCXR1000_1U02.
                    "VIEWPROC_ZVCXR1000_1