*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZTFIR1005_1U01.
                    "VIEWFRAME_ZVFIR1005_1
INCLUDE LZTFIR1005_1U02.
                    "VIEWPROC_ZVFIR1005_1