*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZTMME1006_1U01.
                    "VIEWFRAME_ZVMME1006_1
INCLUDE LZTMME1006_1U02.
                    "VIEWPROC_ZVMME1006_1