*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZTFIR1005_3U01.
                    "VIEWFRAME_ZVFIR1005_3
INCLUDE LZTFIR1005_3U02.
                    "VIEWPROC_ZVFIR1005_3