*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZFIC1009_1U01.
                    "ZFIC1009_CARGA_ACTIVOS_FIJOS