*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZVPPR1156_2U01.
                    "VIEWFRAME_ZVPPR1156_2
INCLUDE LZVPPR1156_2U02.
                    "VIEWPROC_ZVPPR1156_2