*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZGFCX_1U01.
                    "ZCX_GETDDICSOURCE
INCLUDE LZGFCX_1U02.
                    "ZCX_CREATE_TRANSPORT_COPY
INCLUDE LZGFCX_1U03.
                    "Z_CX_GET_TRANSPORT_OBJECTS
INCLUDE LZGFCX_1U04.
                    "Z_CX_GET_OBJECT_IN_OPEN_OT
INCLUDE LZGFCX_1U05.
                    "Z_CX_GET_TRANSPORT_INFO
INCLUDE LZGFCX_1U06.
                    "Z_CX_GET_PACKAGE_HIERARCHY
INCLUDE LZGFCX_1U07.
                    "ZCX_GET_DUMP_DETAIL
INCLUDE LZGFCX_1U08.
                    "ZCX_CREATE_TRANSPORT_REQUEST
INCLUDE LZGFCX_1U10.
                    "Z_CX_SEARCH_TRANSPORTS
INCLUDE LZGFCX_1U11.
                    "ZCX_GET_TRANSPORT_LOGS
INCLUDE LZGFCX_1U09.
                    "ZCX_MODIFY_TRANSPORT_REQUEST
INCLUDE LZGFCX_1U12.
                    "Z_CX_GET_PACKAGE_OBJECTS
INCLUDE LZGFCX_1U13.
                    "ZCX_TRACE_TRANSACTION
INCLUDE LZGFCX_1U14.
                    "ZCX_TRACE_ACTIVATE
INCLUDE LZGFCX_1U15.
                    "ZCX_TRACE_DEACTIVATE_AND_READ
INCLUDE LZGFCX_1U16.
                    "ZCX_GET_ENHANCEMENT_SOURCE
INCLUDE LZGFCX_1U17.
                    "ZCX_UTIL_GET_BADI_IMPL
INCLUDE LZGFCX_1U18.
                    "ZCX_UTIL_GET_DMEE_TREE