*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZTCXR1004_1U01.
                    "TABLEFRAME_ZTCXR1004_1
INCLUDE LZTCXR1004_1U02.
                    "TABLEPROC_ZTCXR1004_1