@AbapCatalog.sqlViewName: 'ZPSDR1085_2'
@AbapCatalog.compiler.compareFilter: true
@AbapCatalog.preserveKey: true
@AccessControl.authorizationCheck: #CHECK
@EndUserText.label: 'Material talla color x Cliente'
define view ZPSDR1085_MATALLACOLOR_CLIENTE
  as select from ZCMM_3
{
  key    ZCMM_3.Matnr,
  key    ZCMM_3.Idioma,
  key    ZCMM_3[inner]._caractCliente.IdConvCliente,
         ZCMM_3.Ersda,
         ZCMM_3.Laeda,
         ZCMM_3.Mtart,
         ZCMM_3.Mbrsh,
         ZCMM_3.Matkl,
         ZCMM_3.Bismt,
         ZCMM_3.Meins,
         ZCMM_3.Volum,
         ZCMM_3.Voleh,
         ZCMM_3.Ean11,
         ZCMM_3.Satnr,
         ZCMM_3.Attyp,
         ZCMM_3.Sgt_csgr,
         ZCMM_3.Brgew,
         ZCMM_3.Gewei,
         ZCMM_3.Laeng,
         ZCMM_3.Breit,
         ZCMM_3.Hoehe,
         ZCMM_3.Meabm,
         ZCMM_3.Taklv,
         ZCMM_3.Inhme,
         ZCMM_3.Inhal,
         ZCMM_3.MtposMara,
         ZCMM_3.Sgt_covsa,
         ZCMM_3.Mhdrz,
         ZCMM_3.MEAN11,
         ZCMM_3.MEANTP,
         ZCMM_3.MHPEAN,
         ZCMM_3.FshMgAt1,
         ZCMM_3.Attrib1Text,
         ZCMM_3.FshMgAt2,
         ZCMM_3.Attrib2Text,
         ZCMM_3.FshMgAt3,
         ZCMM_3.Attrib3Text,
         ZCMM_3.ColorAtinn,
         ZCMM_3.Size1Atinn,
         ZCMM_3.Size2Atinn,
         ZCMM_3.Color,
         ZCMM_3.Size1,
         ZCMM_3.Size2,
         ZCMM_3.BrandId,
         ZCMM_3.Brand_descr,
         ZCMM_3.Fashgrd,
         ZCMM_3.Fashgrd_text,
         ZCMM_3.Descripcion,
         ZCMM_3.DescrGrArticulo,
         ZCMM_3.Talla,
         ZCMM_3.DescripcionTalla,
         ZCMM_3.DescripcionColor,
         ZCMM_3.IdConvMaterial,
         ZCMM_3.PosClasificacion,
         ZCMM_3.SizeForCarelabel,
         /* Associations */
         ZCMM_3[inner]._caractCliente.TallaCaracteristica,
         ZCMM_3[inner]._caractCliente.TallaDescripcionCaract,
         ZCMM_3[inner]._caractCliente.ColorCaracteristica,
         ZCMM_3[inner]._caractCliente.ColorDescripcionCaract
}
