*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZFII1008_2U01.
                    "ZCX_ZTMMI1009_1_WRITE_DOCUMENT