*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZCXR1002_2U01.
                    "ZCX_ZTCXR1002_1_WRITE_DOCUMENT