*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZTPPR1156_2U01.
                    "ZPP_ZTPPR1156_2_WRITE_DOCUMENT