*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZVCXR1000_2U01.
                    "VIEWFRAME_ZVCXR1000_2
INCLUDE LZVCXR1000_2U02.
                    "VIEWPROC_ZVCXR1000_2