*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZVPPR1156_1U01.
                    "VIEWFRAME_ZVPPR1156_1
INCLUDE LZVPPR1156_1U02.
                    "VIEWPROC_ZVPPR1156_1