*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZTPPR1156_1_OLOGU01.
                    "ZPP_ZTPPR1156_1_WRITE_DOCUMENT