*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZSDR1135_1U01.
                    "ZSDR1135_ECOMMERCE_INVENTARIO