*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZCXR1000_1U01.
                    "ZCX_ZTCXR1000_1_WRITE_DOCUMENT