*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZTFIR1005_4U01.
                    "VIEWFRAME_ZVFIR1005_4
INCLUDE LZTFIR1005_4U02.
                    "VIEWPROC_ZVFIR1005_4