*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZFIE1002U01.
                    "ZFI_00001120
INCLUDE LZFIE1002U02.
                    "ZFI_00001140