*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZFII1008_1U01.
                    "ZFII1008_VERIFICALIMITECREDITO
INCLUDE LZFII1008_1U02.
                    "ZFII1008_ACTUA_HOMOLOGA_BP_AFS